// Candidate data for 2026 races
// Keys are Kalshi event tickers. dem/rep have name and optional url (campaign website).
// Data compiled from Ballotpedia, 270toWin, FEC, and news sources. Updated March 2026.

const CANDIDATES = {
  // ===================== SENATE RACES =====================

  // --- Toss-Up / Lean ---
  'SENATEOHS-26': { dem: { name: 'Sherrod Brown', url: 'https://www.sherrodbrown.com/' }, rep: { name: 'Jon Husted' } },
  'SENATEAK-26':  { dem: { name: 'Mary Peltola', url: 'https://marypeltola.com/' }, rep: { name: 'Dan Sullivan' } },
  'SENATEIA-26':  { dem: { name: 'TBD (Primary)', url: '' }, rep: { name: 'TBD (Primary)' } },
  'SENATETX-26':  { dem: { name: 'James Talarico', url: 'https://www.talarico.com/' }, rep: { name: 'Cornyn / Paxton (Runoff)' } },
  'SENATEME-26':  { dem: { name: 'Janet Mills', url: 'https://janetmills.com/' }, rep: { name: 'Susan Collins' } },

  // --- Likely / Competitive ---
  'SENATEGA-26':  { dem: { name: 'Jon Ossoff', url: 'https://electjon.com/' }, rep: { name: 'TBD (Primary)' } },
  'SENATEMI-26':  { dem: { name: 'TBD (Primary)', url: '' }, rep: { name: 'Mike Rogers' } },
  'SENATENC-26':  { dem: { name: 'Roy Cooper', url: 'https://roycooper.com/' }, rep: { name: 'Michael Whatley' } },
  'SENATENH-26':  { dem: { name: 'Chris Pappas', url: 'https://chrispappas.org/' }, rep: { name: 'TBD (Primary)' } },
  'SENATENE-26':  { dem: { name: 'Dan Osborn (I)', url: 'https://www.osbornforsenate.com/' }, rep: { name: 'Pete Ricketts' } },
  'SENATEMT-26':  { dem: { name: 'TBD (Primary)', url: '' }, rep: { name: 'Kurt Alme' } },
  'SENATEKS-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Jerry Moran' } },
  'SENATESC-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Lindsey Graham' } },
  'SENATEMN-26':  { dem: { name: 'TBD (Primary)', url: '' }, rep: { name: 'TBD (Primary)' } },

  // --- Safe ---
  'SENATEMS-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Roger Wicker' } },
  'SENATEIL-26':  { dem: { name: 'TBD (Primary)', url: '' }, rep: { name: 'TBD' } },
  'SENATEOR-26':  { dem: { name: 'Jeff Merkley', url: 'https://www.jeffmerkley.com/' }, rep: { name: 'TBD' } },
  'SENATELA-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Bill Cassidy' } },
  'SENATESD-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Mike Rounds' } },
  'SENATENJ-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'SENATEWV-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Shelley Moore Capito' } },
  'SENATERI-26':  { dem: { name: 'Jack Reed', url: 'https://www.reed.senate.gov/' }, rep: { name: 'TBD' } },
  'SENATECO-26':  { dem: { name: 'John Hickenlooper', url: 'https://hickenlooper.senate.gov/' }, rep: { name: 'TBD' } },
  'SENATETN-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Marsha Blackburn' } },
  'SENATEVA-26':  { dem: { name: 'Mark Warner', url: 'https://www.warner.senate.gov/' }, rep: { name: 'TBD' } },
  'SENATEOK-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'James Lankford' } },
  'SENATEAR-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Tom Cotton' } },
  'SENATEDE-26':  { dem: { name: 'Chris Coons', url: 'https://www.coons.senate.gov/' }, rep: { name: 'TBD' } },
  'SENATEID-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Jim Risch' } },
  'SENATEMA-26':  { dem: { name: 'Ed Markey', url: 'https://www.markey.senate.gov/' }, rep: { name: 'TBD' } },
  'SENATEWY-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'John Barrasso' } },
  'SENATEAL-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Tommy Tuberville' } },
  'SENATENM-26':  { dem: { name: 'Martin Heinrich', url: 'https://www.heinrich.senate.gov/' }, rep: { name: 'TBD' } },

  // ===================== HOUSE RACES =====================
  // Key competitive districts

  // --- Toss-Ups ---
  'HOUSEOH9-26':   { dem: { name: 'Marcy Kaptur', url: 'https://kaptur.house.gov/' }, rep: { name: 'TBD (Primary)' } },
  'HOUSEMI10-26':  { dem: { name: 'TBD (Primary)', url: '' }, rep: { name: 'TBD (Primary)' } },
  'HOUSETX15-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Monica De La Cruz' } },
  'HOUSENC1-26':   { dem: { name: 'Don Davis', url: 'https://dondavisforcongress.com/' }, rep: { name: 'TBD' } },
  'HOUSEME2-26':   { dem: { name: 'TBD (Primary)', url: '' }, rep: { name: 'TBD (Primary)' } },
  'HOUSEMT1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Ryan Zinke' } },
  'HOUSEPA8-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Rob Bresnahan' } },
  'HOUSENJ7-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Thomas Kean Jr.' } },
  'HOUSECO3-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Jeff Hurd' } },
  'HOUSENY17-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Mike Lawler' } },
  'HOUSENY22-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Brandon Williams' } },
  'HOUSEMI7-26':   { dem: { name: 'Curtis Hertel', url: 'https://curtishertel.com/' }, rep: { name: 'TBD' } },
  'HOUSEFL23-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSEIA1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Mariannette Miller-Meeks' } },
  'HOUSEAZ2-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Eli Crane' } },
  'HOUSEAZ6-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Juan Ciscomani' } },
  'HOUSETX34-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSEIA3-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Zach Nunn' } },
  'HOUSEPA1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Brian Fitzpatrick' } },
  'HOUSEWI1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Bryan Steil' } },
  'HOUSEOH1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSEFL13-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Anna Paulina Luna' } },
  'HOUSETX28-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSECA22-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'John Duarte' } },
  'HOUSENY4-26':   { dem: { name: 'TBD', url: '' }, rep: { name: "Anthony D'Esposito" } },
  'HOUSEMI4-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSECO8-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Gabe Evans' } },
  'HOUSEAZ1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'David Schweikert' } },
  'HOUSECA40-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Young Kim' } },
  'HOUSEWI3-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Derrick Van Orden' } },
  'HOUSEPA7-26':   { dem: { name: 'Susan Wild', url: 'https://wildforcongress.com/' }, rep: { name: 'TBD' } },
  'HOUSEVA1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Rob Wittman' } },
  'HOUSEWA3-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Joe Kent' } },
  'HOUSENM2-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Yvette Herrell' } },
  'HOUSEPA10-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Scott Perry' } },
  'HOUSEMI3-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSECA21-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Jim Costa' } },
  'HOUSENH1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSENEV3-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSEIN1-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSENE2-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Don Bacon' } },
  'HOUSENY3-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Tom Suozzi' } },
  'HOUSENJ5-26':   { dem: { name: 'Josh Gottheimer', url: 'https://www.gottheimer.com/' }, rep: { name: 'TBD' } },
  'HOUSEOH13-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSENY19-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Marc Molinaro' } },
  'HOUSEMN2-26':   { dem: { name: 'Angie Craig', url: 'https://angiecraig.com/' }, rep: { name: 'TBD' } },
  'HOUSEPA17-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSEOR5-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Lori Chavez-DeRemer' } },
  'HOUSECA13-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'John Duarte' } },
  'HOUSENJ9-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSEVA2-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Jen Kiggans' } },
  'HOUSEIL17-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Eric Sorensen' } },
  'HOUSENEV4-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSEVA7-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSECA45-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Michelle Steel' } },
  'HOUSEMI8-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
  'HOUSECA49-26':  { dem: { name: 'Mike Levin', url: 'https://mikelevin.org/' }, rep: { name: 'TBD' } },
  'HOUSECA3-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'Kevin Kiley' } },
  'HOUSENEV1-26':  { dem: { name: 'Dina Titus', url: 'https://titus.house.gov/' }, rep: { name: 'TBD' } },
  'HOUSECA47-26':  { dem: { name: 'Dave Min', url: 'https://davemin.com/' }, rep: { name: 'TBD' } },
  'HOUSECA41-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Ken Calvert' } },
  'HOUSECA27-26':  { dem: { name: 'TBD', url: '' }, rep: { name: 'Mike Garcia' } },
  'HOUSECT5-26':   { dem: { name: 'Jahana Hayes', url: 'https://jahanahayes.com/' }, rep: { name: 'TBD' } },
  'HOUSECA9-26':   { dem: { name: 'Josh Harder', url: 'https://joshharder.com/' }, rep: { name: 'TBD' } },
  'HOUSENY18-26':  { dem: { name: 'Pat Ryan', url: 'https://www.patryanforcongress.com/' }, rep: { name: 'TBD' } },
  'HOUSENH2-26':   { dem: { name: 'TBD', url: '' }, rep: { name: 'TBD' } },
};
